#!/bin/bash

# Author: Priyansu Sahoo
# Data Created: 10/11/2022
# Last Modified: 10/11/2022

# Description
# Backup all files in your home directory and save them all in a .tar archive.

# Usage
# Backup Script

mkdir /home/ps/GitHub/BashScripts/backup_test/
cp -r /home/ps/GitHub/PythonIn30Days /home/ps/GitHub/BashScripts/backup_test/
# cd /home/ps/GitHub/BashScripts/backup_test/
# tar -cvf ~/backup_test/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

exit 0
